alertmanager:
  config:
    global:
      resolve_timeout: 5m

    route:
      group_by: ['alertname']
      group_interval: 5m
      repeat_interval: 1h
      receiver: webhook
      routes:
        # Route for critical alerts (to both webhook and Slack)
        - match:
            severity: critical
          receiver: webhook
        - match:
            severity: critical
          receiver: slack
        
        # Route for all other alerts
        - match_re:
            alertname: ".*"
          receiver: webhook
    
    receivers:
      - name: webhook
        webhook_configs:
          - url: 'https://jqqsjk2vdf.execute-api.ap-south-1.amazonaws.com/dev/prometheus-alerts'

      - name: slack
        slack_configs:
          - send_resolved: true
            api_url: 'https://hooks.slack.com/services/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'
            channel: '#prod-alerts'
            text: |-
              *Alert:* {{ .CommonAnnotations.summary }}
              *Description:* {{ .CommonAnnotations.description }}
              *Severity:* {{ .CommonLabels.severity }}

  alertmanagerSpec:
    # Selects Alertmanager configuration based on these labels. Ensure that the Alertmanager configuration has matching labels.
    # ✅ Solves error: Misconfigured Alertmanager selectors can lead to missing alert configurations.
    # ✅ Solves error: Alertmanager wasn't able to findout the applied CRD (kind: Alertmanagerconfig)
    alertmanagerConfigSelector:
      matchLabels:
        release: monitoring

    # Sets the number of Alertmanager replicas to 3 for high availability.
    # ✅ Solves error: Single replica can cause alerting issues during pod failures.
    # ✅ Solves error: Alertmanager Cluster Status is Disabled (GitHub issue)
    replicas: 2

    # Sets the strategy for matching Alertmanager configurations. 'None' means no specific matching strategy.
    # ✅ Solves error: Incorrect matcher strategy can lead to unhandled alert configurations.
    # ✅ Solves error: Get rid of namespace matchers when creating AlertManagerConfig (GitHub issue)
    alertmanagerConfigMatcherStrategy:
      type: None

# Service configurations for NodePort
prometheus:
  service:
    type: NodePort
    nodePort: 30000

alertmanager:
  service:
    type: NodePort
    nodePort: 32000

grafana:
  service:
    type: NodePort
    nodePort: 31000

prometheus-node-exporter:
  service:
    type: NodePort
    nodePort: 32001
